//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba1.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTransporte()
        {
            this.tbViajes = new HashSet<tbViajes>();
        }
    
        public int trasnporte_id { get; set; }
        public Nullable<int> unidad { get; set; }
        public string conductor { get; set; }
        public Nullable<double> tarifa { get; set; }
        public Nullable<double> bono { get; set; }
        public Nullable<int> meta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbViajes> tbViajes { get; set; }
    }
}
